name: Update V2Ray Subscription

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 2:00 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  update_v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 使用最新版本

      - name: Set up Python
        uses: actions/setup-python@v4  # 使用最新版本
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run process_v2ray.py
        run: python python/process_v2ray.py

      - name: Check for changes and commit if needed
        id: commit_changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add json/v2ray
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update V2Ray subscription file"
            echo "Changes detected, committing."
            echo "changed=true" >> $GITHUB_ENV  # 使用环境文件设置输出变量
          else
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Push changes
        if: env.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main || echo "Push failed; may be due to permissions or branch protection."
