name: V2Ray Subscription Update

on:
  schedule:
    - cron: '0 1 * * *'  # 每小时执行一次
    workflow_dispatch:  # 允许手动触发


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install requests
        run: |
          pip3 install requests

      - name: Run V2Ray processing script
        run: |
          python3 process_v2ray.py

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add json/v2ray
          git commit -m "Update V2Ray subscription file"
          git push
