name: V2Ray Subscription Update

on:
  schedule:
    - cron: '0 2 * * *'  # 每天的 2:00 AM 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用最新版本

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install requests
        run: |
          pip3 install requests

      - name: Run V2Ray processing script
        run: |
          python3 python/process_v2ray.py

      - name: Compare files
        run: |
          if cmp -s json/v2ray json/v2ray.new; then
            echo "Files are identical; no update needed."
            exit 0
          else
            echo "Files differ; proceeding to update."
            mv json/v2ray.new json/v2ray  # 用新文件替换旧文件
          fi

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add json/v2ray
          git commit -m "Update V2Ray subscription file" || echo "No changes to commit"
          git push
