name: Update V2Ray Subscription

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 2:00 执行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 确保有推送权限

jobs:
  update_v2ray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保检出完整历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run process_v2ray.py
        run: |
          python python/process_v2ray.py  # 确保替换为您的脚本路径
        continue-on-error: true  # 允许脚本失败以便查看详细日志

      - name: Check v2ray file content
        run: cat json/v2ray  # 确保 v2ray 文件存在并查看内容

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add json/v2ray
          git commit -m 'Update V2Ray subscription file' || echo "No changes to commit."
          git push origin main || echo "Push failed; may be due to permissions or branch protection."
